### ISSUE TITLE
mods

### ISSUE THREAD

**Issue by pintoso** [tetosama/Palworld-Server-Modding#1]
Are you sure the mods are working for you? Im trying to zero out the stamina cost of jumping, but its not working:

```lua
ExecuteAsync(function()
    GameSettingInstance = FindFirstOf("PalGameSetting")
    GameSettingInstance.JumpSP = 0
end)
```

**Comment by tetosama** [comment]
Could it be client-sided? I'll check it out later.

**Comment by tetosama** [comment]
Here's another mod that stops Stomach from decreasing and it's working:

```
ExecuteAsync(function()
    GameSettingInstance = FindFirstOf("PalGameSetting")
    GameSettingInstance.StomachDecreace_perSecond_Player = 0.0
end)
```

I think the issue is whether the stamina is localized, or the real variable that's getting used is somewhere else.

**Comment by pintoso** [comment]
> Here's another mod that stops Stomach from decreasing and it's working:
> 
> ```
> ExecuteAsync(function()
>     GameSettingInstance = FindFirstOf("PalGameSetting")
>     GameSettingInstance.StomachDecreace_perSecond_Player = 0.0
> end)
> ```
> 
> I think the issue is whether the stamina is localized, or the real variable that's getting used is somewhere else.

Yes.
I imagine that stamina is client-side.
Is there a more practical way to determine if the function is client or server-side?

**Comment by tetosama** [comment]
> > Here's another mod that stops Stomach from decreasing and it's working:
> > ```
> > ExecuteAsync(function()
> >     GameSettingInstance = FindFirstOf("PalGameSetting")
> >     GameSettingInstance.StomachDecreace_perSecond_Player = 0.0
> > end)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think the issue is whether the stamina is localized, or the real variable that's getting used is somewhere else.
> 
> Yes. I imagine that stamina is client-side. Is there a more practical way to determine if the function is client or server-side?

You'll need to figure it out by testing or reverse engineering. In my opinion, testing is more practical
